name: Continental Reporters
favicon: null
layout_spectrum: 0.10665
typography_spectrum: 0.17906
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f1f0f6'
    - '#1c1d22'
    - '#acbbb4'
    - '#ab6d56'
    - '#e29c75'
  brandStrength: 0.5
  lightness: 0.9375
  saturation: 0.313063
  rhythmicContrast: 1
purpose: []
