typography_spectrum: 0.74658
color:
  brandColors:
    - '#ff2200'
    - '#000000'
    - '#00ff00'
    - '#008000'
    - '#ffffff'
  brandStrength: 0.625
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.25
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.64481
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Egerue Nnamdi
  email: egerueonline@yahoo.com
name: Continental Reporters
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose:
  - type: contact
    url: 'tel:+2348162561172'
    label: Call +2348162561172
  - type: contact
    url: 'mailto:egerueonline@yahoo.com'
    label: Contact me
