name: Continental Reporters
favicon: null
layout_spectrum: 0.10665
typography_spectrum: 0.17906
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff2200'
    - '#000000'
    - '#00ff00'
    - '#008000'
    - '#ffffff'
  brandStrength: 0.0625
  lightness: 0.9375
  saturation: 0.313063
  rhythmicContrast: 1
purpose: []
