analytics: {}
color:
  brandColors:
    - '#f1f0f6'
    - '#1c1d22'
    - '#acbbb4'
    - '#ab6d56'
    - '#e29c75'
  brandStrength: 0.75
  lightness: 0.8125
  rhythmicContrast: 1
  saturation: 0.125
cta: {}
layout_spectrum: 0.015765
name: Continental Reporters
opengraph: {}
purpose: []
typography_spectrum: 0.23973
