name: Egerue Nnamdi
favicon: null
layout_spectrum: 0.48434
typography_spectrum: 0.23973
title: Continental Reporters
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f1f0f6'
    - '#1c1d22'
    - '#acbbb4'
    - '#ab6d56'
    - '#e29c75'
  brandStrength: 0.75
  lightness: 0.8125
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
