name: Continental Reporters
favicon: null
layout_spectrum: 0.64481
typography_spectrum: 0.74658
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff2200'
    - '#000000'
    - '#00ff00'
    - '#008000'
    - '#ffffff'
  brandStrength: 0.625
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
