name: Continental Reporters
favicon: null
layout_spectrum: 0.80137
typography_spectrum: 0.17906
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff2200'
    - '#000000'
    - '#00ff00'
    - '#008000'
    - '#ffffff'
  brandStrength: 0.4375
  lightness: 0.5
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
